# Generated by Django 3.2.6 on 2021-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgtasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='images/')),
                ('expire_date', models.DateField()),
                ('expire', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
