# Generated by Django 3.2.6 on 2021-09-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgtasks', '0002_doument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doument',
            new_name='Document',
        ),
    ]
