# Generated by Django 5.2 on 2025-04-22 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=128)),
                ("country", models.CharField(max_length=32)),
                ("zip_code", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("HOUSE", "House"),
                            ("APARTMENT", "Apartment"),
                            ("CONDO", "Condominium"),
                            ("TOWNHOUSE", "Townhouse"),
                            ("LAND", "Land"),
                        ],
                        max_length=20,
                    ),
                ),
                ("square_feet", models.PositiveIntegerField()),
                ("bedrooms", models.PositiveSmallIntegerField()),
                ("bathrooms", models.PositiveSmallIntegerField()),
                ("has_garage", models.BooleanField(default=False)),
                ("has_balcony", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estates.location",
                    ),
                ),
            ],
        ),
    ]
