# Generated by Django 3.2.6 on 2025-04-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
