# Generated by Django 3.2.6 on 2021-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djorm', '0002_bookmodel_cupboardmodel_productclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupboardmodel',
            name='m2m',
            field=models.ManyToManyField(related_name='cupboardmodel', related_query_name='cupboardmodel', to='djorm.ProductClass'),
        ),
    ]
