# Generated by Django 3.2.6 on 2021-08-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djorm', '0002_book_bookcontent_bookorders_isbn_itema_itemb_itemc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='isbn',
            name='article_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='djorm.article'),
            preserve_default=False,
        ),
    ]
