# Generated by Django 3.2.6 on 2021-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djorm', '0003_cupboardmodel_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='m2m',
            field=models.ManyToManyField(related_name='bookmodel', related_query_name='bookmodel', to='djorm.ProductClass'),
        ),
    ]
