# Generated by Django 3.2.6 on 2021-08-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djorm', '0005_artproject_project_researchproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payor', models.CharField(max_length=255)),
                ('payee', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
