# Generated by Django 3.2.6 on 2021-08-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djorm', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
