# Generated by Django 3.2.6 on 2021-10-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djorm', '0009_aggregationbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('age', models.CharField(max_length=255, verbose_name='age')),
            ],
        ),
    ]
