# Generated by Django 3.2.6 on 2021-09-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pysignals', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.PositiveIntegerField(blank=True)),
                ('total_price', models.PositiveIntegerField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('cars', models.ManyToManyField(to='pysignals.Car')),
            ],
        ),
    ]
