# Generated by Django 3.2.6 on 2021-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djs', '0002_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
