# Generated by Django 3.2.6 on 2021-08-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('country_id', models.CharField(max_length=1, null=True)),
                ('manufacturer_id', models.CharField(max_length=6, null=True)),
                ('number_id', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
