# Generated by Django 3.2.6 on 2021-08-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0003_alter_sale_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quantitty',
            new_name='quantity',
        ),
    ]
